### ISSUE TITLE
deferred=true does not write to file

### ISSUE THREAD

**Issue by yudiell** [mulesoft-labs/data-weave-cli#40]
When you set the deferred=true in the dw script it outputs nothing.

Example:
curl "https://api.github.com/repos/mulesoft/mule/commits?per_page=5" | dw > response.json "output application/json deferred=true --- payload"

Your response is greatly appreciated.

**Comment by yudiell** [comment]
Hello @machaval,
Thanks for the reply.
I am trying to use it for memory management.

**Comment by machaval** [comment]
So deferred doesn't apply on the cli because what it doesn't is it defers the output until is required by a consumer of the output. But in your case if you output to a file or the standard output is the same. It wan't make any difference in terms of the memory management.

**Comment by yudiell** [comment]
I am trying to replicate this scenario.
![dw](https://user-images.githubusercontent.com/9805143/170508177-194f05ef-d24d-4e12-83da-2dd8c328815e.png)

So I don't run into this:
![dw_outofmemmory](https://user-images.githubusercontent.com/9805143/170508263-ed673775-0447-4975-9b75-0002ebaa594b.png)
