### ISSUE TITLE
--file help is incorrect

### ISSUE THREAD

**Issue by dev-juha** [mulesoft-labs/data-weave-cli#50]
**Describe the bug**
 -f,--file <file-path>                     
**Specifies output file** for the
transformation if not standard
output will be used.

**To Reproduce**
1. dw --help

**Expected behavior**
Specifies the
transformation file containing dataweave to be used.

**Desktop (please complete the following information):**
 - OS:  iOS

**Comment by machaval** [comment]
Hi Thanks for this we will take a look at it
