### ISSUE TITLE
open-source channel in slack doesn't seem to exist

### ISSUE THREAD

**Issue by ksully-execute** [mulesoft-labs/data-weave-cli#66]
there doesn't seem to be an open-source channel in slack....can you update us as to how the open-source is going and when a release is expected?

**Comment by machaval** [comment]
Hi @ksully-execute  I will create a channel where we can add any updates and news on this. We are working on  it but the infrastructure is taking more time that we expected to.

**Comment by ksully-execute** [comment]
Sounds good, thanks!

**Comment by rhoegg** [comment]
There are two now, #opensource and #open-source.  I think this issue can be closed :)
