### ISSUE TITLE
Re-add the --path parameter

### ISSUE THREAD

**Issue by scipper** [mulesoft-labs/data-weave-cli#80]
**Is your feature request related to a problem? Please describe.**
In previous verions of data-weave-cli (at least in 1.0.19) it was possible to add a folder with --path, where the cli searches for scripts. This was a very useful feature. 

**Describe the solution you'd like**
Re-add the --path parameter.

**Describe alternatives you've considered**
Alternatively allow more than one file for the -f / --file parameter

**Additional context**
The --path functionality was removed with this PR: https://github.com/mulesoft-labs/data-weave-cli/pull/27
Why?

**Comment by machaval** [comment]
This has been fixed on latest version
